const langAM = {
    en:
    {
        addSelectedOption: 'Add selected element',
        noOption: 'No accounting items added',
        noName: 'No name',
        nameField: 'Field name:',
        placeholderNameField: 'Enter name of field',
        editOption: 'Edit option',
        deleteOption: 'Delete element',
        fixField: 'Fix field',
        delAllFields: 'Delete all fields',
        hideField: 'Hide field in accounting',
        hideGroup: 'Hide group in accounting',
        hideElement: 'Hide element in accounting',
        save: 'Save',
        close: 'Close',
        upArrow: 'Move up',
        downArrow: 'Move down',
        msgFixField: 'No fixed fields',
        msgErrorSwitchElem: 'Error in SwitchElem',
        switchElemStep: 'Step',
        switchElemMax: 'Maximum value',
        switchElemMin: 'Minimum value',
        setElement: 'Setting the selected element',
        selectOption: 'Select an option',
        enterNameGroup: 'Enter name of group',
        enterNameElement: 'Enter name of element',
        nameOptionSelect: 'Item name',
        addItem: 'Add item',
        rows: 'Height',
        cols: 'Width',
        beginPage: 'Proceed to menu selection',
        electronVersion: 'Electron version',
        nodeVersion: 'Node version',
        chromiumVersion: 'Chromium version',
        titlePas: 'Password error',
        messagePas: 'The password is incorrect, please try again.',
        buttonsPas: ['Understood'],
        titleChangeSuccessfully: 'Successfully',
        titleChangeUnsuccessfully: 'Unsuccessfully',
        titleChangeWrong: 'Password wrong',
        messageChangeWithout: 'Password changed to no password successfully, click OK to continue.',   
        messageChangeWith: 'Password changed successfully, click OK to continue.', 
        messageChangeUnsuccessfully: 'The passwords to change do not match! Please try again or cancel the action.',
        messageChangeWrong: 'Password is wrong, please try again or cancel!', 
        workDirectory: 'Working directory',
        ln: 'en',
    },
    uk:
    {
        addSelectedOption: 'Додати обраний елемент',
        noOption: 'Немає доданих елементів обліку.',
        noName: 'Немає імені',
        nameField: "Ім'я поля:",
        placeholderNameField: 'Введіть назву поля',
        editOption: 'Редагувати елемент',
        deleteOption: 'Видалити елемент',
        fixField: 'Зафіксувати поле',
        delAllFields: 'Видалити всі поля',
        hideField: 'Сховати поле в обліку даних',
        hideGroup: 'Сховати групу в обліку даних',
        hideElement: 'Сховати елемент в обліку даних',
        save: 'Зберегти',
        close: 'Закрити',
        upArrow: 'Пересунути вгору',
        downArrow: 'Пересунути вниз',
        msgFixField: 'Зафіксованих полів немає',
        msgErrorSwitchElem: 'Помилка в SwitchElem',
        switchElemStep: 'Крок',
        switchElemMax: 'Максимальне значення',
        switchElemMin: 'Мінимальне значення',
        setElement: 'Налаштування обраного елемента',
        selectOption: 'Оберіть опцію',
        enterNameGroup: 'Введіть назву групи',
        enterNameElement: "Введіть ім'я елемента",
        nameOptionSelect: 'Найменування пункту',
        addItem: 'Додати пункт',
        rows: 'Висота',
        cols: 'Ширина',
        beginPage: 'Приступайте до вибору меню', 
        electronVersion: 'Electron версія',
        nodeVersion: 'Node версія',
        chromiumVersion: 'Chromium версія',
        titlePas: 'Помилка паролю',
        messagePas: 'Пароль не вірний, повторіть введення.',
        buttonsPas: ['OK'], 
        titleChangeSuccessfully: 'Успішно',
        titleChangeUnsuccessfully: 'Неуспішно',
        titleChangeWrong: 'Пароль помилковий',
        messageChangeWithout: 'Пароль змінено на відсутність пароля успішно, натисніть OK, щоб продовжити.',   
        messageChangeWith: 'Пароль змінено успішно, натисніть OK для продовження.', 
        messageChangeUnsuccessfully: 'Паролі для зміни не співпадають! Повторіть спробу або скасуйте дію.',
        messageChangeWrong: 'Пароль помилковий, повторіть введення або скасуйте дію!', 
        workDirectory: 'Робоча директорія',
        ln: 'uk'
    },
    ru:
    {
        addSelectedOption: 'Добавить выбранный элемент',
        noOption: 'Нет добавленных элементов учёта.',
        noName: 'Нет имени',
        nameField: 'Имя поля:',
        placeholderNameField: 'Введите имя поля',
        editOption: 'Редактировать элемент',
        deleteOption: 'Удалить элемент',
        fixField: 'Зафиксировать поле',
        delAllFields: 'Удалить все поля',
        hideField: 'Спрятать поле в учёте данных',
        hideGroup: 'Спрятать группу в учёте данных',
        hideElement: 'Спрятать элемент в учёте данных',
        save: 'Сохранить',
        close: 'Закрыть',
        upArrow: 'Переместить вверх',
        downArrow: 'Переместить вниз',
        msgFixField: 'Зафиксированных полей нет',
        msgErrorSwitchElem: 'Ошибка в SwitchElem',
        switchElemStep: 'Шаг',
        switchElemMax: 'Максимальное значение',
        switchElemMin: 'Минимальное Значение',
        setElement: 'Настройка выбранного элемента',
        selectOption: 'Выбирите опцию',
        enterNameGroup: 'Введите название группы',
        enterNameElement: 'Введите имя элемента',
        nameOptionSelect: 'Наименовании пункта',
        addItem: 'Добавить пункт',
        rows: 'Высота',
        cols: 'Ширина',
        beginPage: 'Приступайте к выбору меню',
        electronVersion: 'Electron версия',
        nodeVersion: 'Node версия',
        chromiumVersion: 'Chromium версия', 
        titlePas: 'Ошибка пароля',
        messagePas: 'Пароль не верный, повторите ввод или выходите.',
        buttonsPas: ['Понятно'],   
        titleChangeSuccessfully: 'Успешно',
        titleChangeUnsuccessfully: 'Неспешно',
        titleChangeWrong: 'Пароль ошибочен',
        messageChangeWithout: 'Пароль изменён на отсутствие пароля успешно, нажмите OK для продолжения.',   
        messageChangeWith: 'Пароль изменён успешно, нажмите OK для продолжения..', 
        messageChangeUnsuccessfully: 'Пароли для изменения не совпадают! Повторите попытку или отмените действие.',
        messageChangeWrong: 'Пароль ошибочный, повторите ввод или отмените действие!',
        workDirectory: 'Рабочая директория',
        ln: 'ru'
    }
}
export default langAM